version: '3.8'
services:
  lordhood-client:
    container_name: lordhood.angular   # Set custom container name
    image: lordhoodclient                 # Set custom image name
    build: .
    ports:
      - "4200:80"   # Map port 4200 on your local machine to port 80 in the container
    restart: always
    volumes:
      - .:/app                    # Bind mount the current directory to /app in the container
      - /app/node_modules         # Prevent overwriting node_modules with the host
    environment:
      - NODE_ENV=docker # Set NODE_ENV to 'docker'
     



# docker-compose up --build
# docker-compose up -d --build
