version: '3.8'
services:
  angular-app:
    build: .
    ports:
      - "4200:80"   # Map port 4200 on your local machine to port 80 in the container
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
      - /app/node_modules # Persist node_modules inside the container to avoid reinstalling on every start
    environment:
      - NODE_ENV=development # Set NODE_ENV to 'production'
      #  command: "npm run start -- --host 0.0.0.0"  # Make sure Angular listens on all network interfaces
# docker-compose up --build
